celery:
    broker_url: redis://localhost/0
    result_backend: redis://localhost/0

elasticsearch:
    endpoint:
        host: localhost
        port: 9200


collectors:
    # - dummy-docker-collector
    - recon-ng
    - certificate-transparency
    - nmap
    # - dirsearch
    - sherlock
    - infoga
    - harvester
    - subfinder
    - phone-infoga
    - twint
    - zen
    # - littlebrother
    - blackwidow
    # - kupa3
