---
version: '3.5'

networks:
  deploy_engine:
    external: true

services:
#######################
#  CONNECTORS
#######################
    connectors:
        build: .
        volumes:
            - ./salver:/opt/salver/salver:ro
        environment:
            ENV_FOR_DYNACONF: development
        networks:
          - deploy_engine
        command: -m salver.connectors.app

########################
##  ENGINE
########################
    engine:
        build: .
        volumes:
            - ./salver:/opt/salver/salver:ro
        environment:
            ENV_FOR_DYNACONF: development
        networks:
          - deploy_engine
        command: -m salver.engine.app