[tool.black]
use_newline_before_comments = true
line-length = 88
target-version = ['py37', 'py38']
include = '\.pyi?$'

[tool.isort]
src_paths = ["salver"]
line_length = 88
multi_line_output = 3
length_sort = true
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

