---
default:
    opensearch:
        bootstrap_servers: broker:19092

    celery:
      broker_url: redis://:COVOfUJsC8Bnly8aRX4W@redis/0
      result_backend: redis://:COVOfUJsC8Bnly8aRX4W@redis/0

local:
    celery:
      broker_url: redis://:COVOfUJsC8Bnly8aRX4W@localhost:6379/0
      result_backend: redis://:COVOfUJsC8Bnly8aRX4W@localhost:6379/0
