version: "3.3"

services:
########################
##  SUPERADMIN
########################
  superadmin:
    image: nginx
    restart: always
    ports:
      - 127.0.0.1:80:80
    volumes:
      - ./superadmin:/usr/share/nginx/html
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: rootroot

########################
##  MONGODB
########################
  mongo:
    image: mongo
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: rootroot

########################
##  MONGOEXPRESS
########################
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 127.0.0.1:8081:8081
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: rootroot

########################
##  NEO4J
########################
  neo4j:
    image: neo4j:4.2.1
    ports:
      - 127.0.0.1:7474:7474
      - 127.0.0.1:7687:7687
    volumes:
      - neo_data:/data
      - neo_plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/root
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4JLABS_PLUGINS: '["apoc"]'


########################
##  KIBANA
########################
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    ports:
      - 127.0.0.1:5601:5601
    volumes:
     - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - elastic

########################
##  ELASTICSEARCH
########################
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    networks:
      - elastic
    volumes:
      - elastic:/usr/share/elasticsearch/data
    depends_on:
      - kibana

########################
##  FLOWER
########################
  flower:
    image: mher/flower:latest
    ports:
      - 127.0.0.1:5555:5555
    depends_on:
      - redis
    networks:
      - admin
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

########################
##  REDIS
########################
  redis:
    image: redis:latest
    ports:
      - 127.0.0.1:6379:6379
    hostname: redis
    networks:
      - admin

########################
##  REDISINSIGHT
########################
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - 127.0.0.1:8001:8001
    networks:
      - admin


networks:
  elastic:
  admin:

volumes:
  elastic:
    driver: local
  neo_data:
    driver: local
  neo_plugins:
    driver: local
