---
default:
    opensearch:
        bootstrap_servers: broker:19092

    celery:
      broker_url: redis://:COVOfUJsC8Bnly8aRX4W@redis/0
      result_backend: redis://:COVOfUJsC8Bnly8aRX4W@redis/0

    enabled_collectors:
      - dummy-collector
      - dummy-docker-collector
      - sherlock
      - zen
      - recon-ng
      - the-harvester

    logstash:
      ip: logstash
      port: 5042

local:
    celery:
      broker_url: redis://:COVOfUJsC8Bnly8aRX4W@localhost:6379/0
      result_backend: redis://:COVOfUJsC8Bnly8aRX4W@localhost:6379/0

    logstash:
      ip: localhost
      port: 5042