---
default:
    kafka:
    enabled_collectors:

development:
    enabled_collectors:
        - zen
        - dummy-docker-collector
        - dummy-collector

    kafka:
        bootstrap_servers: localhost:9092
        schema_registry_url: http://127.0.0.1:8081

        workers_per_topic: 2
        threads_per_worker: 4
    
    logstash:
        host: localhost
        port: 5042
        batch_size: 20

testing:
    enabled_collectors:
        - dummy-docker-collector
        - dummy-collector

    kafka:
        bootstrap_servers: localhost:9092
        schema_registry_url: http://127.0.0.1:8081
        workers_per_topic: 1
        threads_per_worker: 2
