default:
    collectors_path: salver/modules/collectors
    enabled_collectors:

    celery:
        broker_url: redis://localhost/0
        result_backend: redis://localhost/1

    elasticsearch:
        endpoint:
            host: localhost
            port: 9200

testing:
        enabled_collectors:
            - dummy-docker-collector
            - dummy-collector

dev:
        enabled_collectors:
            - dummy-docker-collector
            - dummy-collector
            - recon-ng
            - certificate-transparency
            #- nmap
            - sherlock
            - infoga
            - harvester
            - subfinder
            - phone-infoga
            - twint
            - zen
            - blackwidow
            #######################
            # broken collectors
            #######################
            # - dirsearch
            # - littlebrother
            # - kupa3
