---
version: '2'
services:
    vault:
        image: vault
        container_name: vault
        ports:
            - 8200:8200
        restart: always
        volumes:

            - ./file:/vault/file
            - ./config:/vault/config
        cap_add:
            - IPC_LOCK
        entrypoint: vault server -config=/vault/config/vault.json
