default:
    refresh_agents_interval: 10
    salver:
        scans_path: ./modules/scans
    celery:
        queue_name: salve_controller
        broker_url: redis://localhost/0
        result_backend: redis://localhost/1
        task_ignore_result: False

        redbeat_redis_url: redis://localhost/2
        beat_scheduler : redbeat.RedBeatScheduler


    elasticsearch:
        endpoint:
            host: localhost
            port: 9200
        kibana_endpoint: http://localhost:5601

    neo4j:
        endpoint: bolt://localhost:7687
        username: neo4j
        password: root

    mongodb:
        endpoint: mongodb://localhost:27017
        database: salver

testing:
    mongodb:
        endpoint: mongodb://localhost:27017
        database: salver-test
